### ISSUE TITLE
KSM and DOT transactions not working on ledger error: 'Txn version not supported'

### ISSUE THREAD

**Issue by didaw** [Zondax/ledger-kusama#106]
Hey, so I deleted my DOT and KSM apps of my Ledger Nano S to make room to install another app today, then when I re-installed it an hour later I now get an error saying 'Txn version not supported' on both apps. I last used Ledger to send some DOT yesterday and I used Ledger to send KSM a few weeks ago.

My DOT version on Ledger is 7.30.0 and KSM 5.30.1 my Ledger version is 1.6.1 and I've also updated my metadata for polkadot.js for both KSM and DOT.

Is anyone else having this issue for both KSM and DOT? really could do with accessing some of my funds if there is a get arround

**Comment by loupiote** [comment]
I have the same issue. Please fix the Kusama and Polkadot apps so that they can sign the new transactions!

See https://www.reddit.com/r/Kusama/comments/qbhzul/ledgner_nano_x_error_txn_version_not_supported/

https://www.reddit.com/r/ledgerwallet/comments/qbn935/kusama_txn_version_not_supported_i_have_the/
