### ISSUE TITLE
Tutorial for exporting BIP39 Kusama keys (Ledger)

### ISSUE THREAD

**Issue by blockchainenthusiast** [Zondax/ledger-kusama#129]
Im having trouble exporting Kusama keys from the ledger. If they are my keys I should have the ability to have migrate to a different wallet as I choose. However right now, it appears there is no way to export my keys from the Ledger. Essentially Ledger is preventing the export of keys or at least not providing assistance to allow people to withdraw their Kusama keys from the device. 

According to Ledger the export is possible if exporting to another wallet that supports the BIP39 or BIP44. When I tried to do this, I was prompted for a derivation path but am unable to find out that the correct path that Ledger uses is. No response from ledger yet, and so I am posting the request here. A simple tutorial on how to properly export the keys from ledger into another non custodial wallet or at the very least the correct derivation path that ledger uses for Kusama accounts.

**Comment by jleni** [comment]
Ledger key derivation is based on standard BIP39 (typical for other coins) and substrate is using a slightly derived approach (rationale is provided here https://github.com/paritytech/substrate-bip39#why)

The substrate compatibility table is provided here:
https://guide.kusama.network/docs/learn-accounts/#portability

This means that there is no mnemonic portability between most substrate tools and Ledger. This is not in the app design but something that applies to Ledger devices in general and due to the differences in the way mnemonics are handled by substrate. Substrate mnemonics are not BIP39.

----

@ainhoa-a @ftheirs we need to write an article about this.

As part of the integration library that we provide to polkadot.js, there are a few specific functions that we created. Other wallets could use these functions to accept BIP39 mnemonics.

Reference: https://github.com/Zondax/ledger-substrate-js/blob/aaf6592d883e345ca1707b6864853a8638bf2e61/src/index.js#L462

At this moment, we are not aware of anything using them.

Although BIP39 is very standard and there are many tools around, we should probably create a small tool (online or CLI) to extract private keys from a BIP39 mnemonic.
