### ISSUE TITLE
Phala sent to kusuma derivation path

### ISSUE THREAD

**Issue by yiedw** [Zondax/ledger-kusama#148]
I connected to khala network using ledger kusama.
And I sent the PHA token of khala to that address.
PHA is currently locked in that address.
When I try to send PHA, I get this error.
I searched and found that we need to find a private key to rescue this PHA.
Could you tell me the derived path so that I can find the private key?
Or is there another good way?

![image](https://user-images.githubusercontent.com/42017660/163961506-3a13ff44-8ff1-42cc-b461-e0ecf3723ffd.png)

**Comment by ftheirs** [comment]
Hi @yiedw, your private key is stored in your Ledger device. Since we haven't developed the Phala app, there is no easy way to recover those funds right now. However.. I have some good news: we are working on a way to recover funds when this kind of issue happens.
I will notify here when I have more updates!

**Comment by ainhoa-a** [comment]
Hi @yiedw we're currently working in the app for Phala.

**Comment by yiedw** [comment]
> Hi @yiedw we're currently working in the app for Phala.

Thx!!! 
Can you tell me once it's done? Please...
